### ISSUE TITLE
UIAA grades should use roman numerals

### ISSUE THREAD

**Issue by musoke** [OpenBeta/sandbag#141]
UIAA grades currently use Latin numerals. They should be Roman.

**Comment by l4u532** [comment]
@musoke I climb in Central Europe, where UIAA is dominant. Hardly anybody uses Roman numerals, simply because they are more cumbersome to read and write. I know, its historic origin is the Weizenbach scale, which then became the UIAA grade system, which are officially denoted in Roman numerals. But in practice, neither climbers, gyms, guide books, nor theCrag use Roman numerals.

**Comment by musoke** [comment]
Ok, thanks for the clarification!

Should Roman numerals be an option that is translated to Arabic?

**Comment by l4u532** [comment]
I do not think so. It's marginal gain (if any, at all), but additional code. In my view, not a sensible trade-off.

**Comment by musoke** [comment]
I'm supportive of reflecting real-world use rather than [a bureaucracy's prescription](https://www.theuiaa.org/grades-standards/rock-climbing/).
