### ISSUE TITLE
Auto release scripts not working

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/sandbag#50]
When it was working before, you can submit a PR with a commit message "[npm release]" and the script will create a tag and publish the new library to NPM registry.

See 
- https://github.com/OpenBeta/sandbag/tree/develop/.github/workflows
- https://github.com/OpenBeta/sandbag/actions

**Comment by DarrenZLew** [comment]
I'm not too familiar with github actions, but following the actions history [here](https://github.com/OpenBeta/sandbag/actions), what seems like happened is that:
- There was a second "New release 2" PR, which was updating the package.json in the develop branch to the latest version 0.0.12. This was due to the automated version bump in the "[npm release 2]" PR right before. 
- This second "New release 2" PR caused the "auto tag based on commit msg" action to run again, which then created a new "v0.0.13" tag in the github repo. See [here](https://github.com/OpenBeta/sandbag/actions/runs/3027371256/workflow) for when that happened.
- Now since there's a "v0.0.13" tag in the github repo, but the develop branch is currently on "v0.0.12", when trying a new "[npm release 3]", the "auto tag based on commit msg" action tries to create a new tag for the repo based on the version in the branch (currently 0.0.12) by bumping it up one. Thus, it tries to create a "v0.0.13" tag, but that already exists, thus the action fails. See [here](https://github.com/OpenBeta/sandbag/actions/runs/3027383186/jobs/4871483422) for when that happened.

1. The "auto tag based on commit msg" action seems to run every time a PR is closed. Does it make sense for this action to only run if the PR has [npm release] in it's head commit message? This would be similar to what the "npm publish action" does, where it has ` if: "startsWith(github.event.head_commit.message, '[npm release]')"`

2. To fix the state of this automation, could we delete the currently created "v0.0.13" tag in the github repo? This would align us back to where we currently are in the develop branch with 0.0.12. So the next time we do an [npm release], it would be able to create a new v0.0.13 tag successfully.

**Comment by DarrenZLew** [comment]
I'll reproduce the state of this repo in my forked version, and see what will need to be updated.

**Comment by vnugent** [comment]
The publish script finally ran to completion😅 !  For future reference we need to explicitly pass individual secrets from the caller job (or turn on `inherit` to pass everything).

https://github.com/OpenBeta/sandbag/blob/develop/.github/workflows/auto-version-bump.yml#L34
