### ISSUE TITLE
add Saxon grades

### ISSUE THREAD

**Issue by musoke** [OpenBeta/sandbag#99]
https://en.wikipedia.org/wiki/Grade_(climbing)#Saxon_grades

**Comment by TaliaMalia** [comment]
Hey @musoke, I would like to partake in your project. 
Could you please assign me to this issue?

**Comment by musoke** [comment]
I have assigned it to you. Let us know if you need help.

**Comment by TaliaMalia** [comment]
Thank you!
This is my very first issue, so you will probably hear from me :)

**Comment by TaliaMalia** [comment]
Hey, 
how do I add data to the routes?
I want to add the saxon grades, but I have difficulty importing the csv file to a database.
When I tried to import it a window opened in my IDE and expected me to choose a "Target Schema", but there are none to choose.
I also tried to add a column in the window that opened in the IDE, but it wouldn't let me change the data record.
How do I move forward now?

![Bildschirmfoto 2023-04-25 um 15 55 57](https://user-images.githubusercontent.com/131688085/234300187-1a2b7592-9fa2-452f-a098-a8be6d86d467.png)

**Comment by musoke** [comment]
This looks like an editor-specific issue.  You can use libreoffice/exel/your favourite text editor to add a column to data/routes.csv.  Then use https://github.com/OpenBeta/sandbag/blob/e153d97b727e77f339697b848ddbaa53fda67bd4/src/data/csvtojson.ts to convert it to JSON.  The JSON is what is used internally.

**Comment by TaliaMalia** [comment]
Thank you, I will look into it later today!

**Comment by TaliaMalia** [comment]
So... after updating the json/csv files I added Saxon to the scales and adjusted everything so I could run some tests. All tests, including the new one I added are running. However when I try to commit my changes I get a jest error saying that the test suite failed to run due to non existing tests in the .d.ts files (which there should be none right?). I tried to adjust jest.config.cjs, so that it would ignore the .d.ts files, but it's still not working. I would appreciate it if you could look over the screenshots to tell me if I am doing something wrong and help me figure out how to resolve this :)
![Bildschirmfoto 2023-04-28 um 15 21 40](https://user-images.githubusercontent.com/131688085/235164517-3e65c206-06ac-4ba3-9793-d316b2910ee5.png)
![Bildschirmfoto 2023-04-28 um 15 26 41](https://user-images.githubusercontent.com/131688085/235164539-0efb3a30-9ae3-4240-ad23-941440497cb8.png)

**Comment by musoke** [comment]
Looks like good progress. 

How did you run the tests?  I use `yarn test`.

**Comment by TaliaMalia** [comment]
I also use yarn test. These are the results: 
The 10 failed test are all the .d.td files from the tests.
![Bildschirmfoto 2023-04-28 um 18 24 51](https://user-images.githubusercontent.com/131688085/235202502-03a88cdd-761e-4501-b276-3ea49c923c74.png)

**Comment by musoke** [comment]
That's odd.  Could you make a draft pull request so we can see your changes?

**Comment by TaliaMalia** [comment]
I would, but I unfortunately can't commit any changes. When I try, the errors from the failed tests prevent me from committing and nothing I tried worked so far.

**Comment by vnugent** [comment]
you can commit with `--no-verify` to bypass the pre-commit checks.  Example:
```bash
git commit --no-verify -am "<commit message>"
```

**Comment by TaliaMalia** [comment]
Thank you, that worked! I was not quite sure if I was allowed to use --no--verify, because I read that it was a bit risky to use it.

I currently have some problems with pushing the changes. I will work on that in the upcoming days and report back to you.

**Comment by musoke** [comment]
> I was not quite sure if I was allowed to use --no--verify, because I read
that it was a bit risky to use it.

You're right that is generally not good practice, but in this case you do
want to push the unverified changes so we can take a look

**Comment by TaliaMalia** [comment]
I was finally able to send you a push draft. My SSH key was not set up correctly, but it should work now. 
Just so you know and don't wonder, I changed a few lines in ewbank.ts in the getGrade function, because I got a type error after updating the json values. I had to use type assertion to make sure that the ewbank property would always be returned as a string. Somehow this only occurred in the ewbank.ts.

**Comment by TaliaMalia** [comment]
Hey, I was just going through routes.json one last time to make sure that the values were matching the score and the values from the grade conversion table and saw that the score and the grade bands were not matching. You can see in the screenshot that with a score of < 54 you should classify as beginner. In the json file however the score of 36 equals the band “intermediate". I tried to retrace the datasource for the score, but I was not able to find it. 
![Bildschirmfoto 2023-05-02 um 13 49 01](https://user-images.githubusercontent.com/131688085/235662751-61e5ce5f-88b6-4510-879a-5213c225b714.png)
![Bildschirmfoto 2023-05-02 um 13 49 54](https://user-images.githubusercontent.com/131688085/235662777-e616f5a0-81c5-4a0c-93fa-1104266dfa17.png)

**Comment by musoke** [comment]
Don't worry about the grade bands, we're actually in the process of
removing them
